kind: pipeline
steps:
- name: run-sh
  image: node:alpine
  commands: 
    - chmod +x ./bin/run.sh
    - ./bin/run.sh
    - env
- name: docker  
  image: plugins/docker
  settings:
    username: oauth
    password: AQAAAAACk7pNAATuwbiYaYaJWUORjzlU2iBxw3k
    repo: cr.yandex/crpu0i3q8v54vgieicbm/site
    tags:
    - ${DRONE_COMMIT_BRANCH}
    registry: cr.yandex
