menu:
  Главная: /
  Архивы: /archives
  Категории: /categories
  Теги: /tags

# 站点次标题和打字动效
# https://github.com/mattboldt/typed.js
subtitle:
  enable: false # 是否开启动效

share_china: false 
share_eng: false

toc: true

yandex_analytics: false

lock:
  enable: false
  password: 123456