menu:
  Главная: /
  Архивы: /archives
  Категории: /categories
  Теги: /tags

# 站点次标题和打字动效
# https://github.com/mattboldt/typed.js
subtitle:
  enable: true # 是否开启动效
  text: 1 # 显示的文字
  text2: 2 # 滚动播放，如果不需要可以留空
  text3: 3 # 最多支持三段文字
  startDelay: 0 # 延迟时间
  typeSpeed: 200 # 打字速度
  loop: true # 是否循环
  backSpeed: 100 # 回退速度
  showCursor: true # 是否显示光标